// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package query

import (
	"time"
)

type Column struct {
	Namespace string
	Col       string
	Type      string
	CreatedAt time.Time
}

type File struct {
	Enabled   bool
	Namespace string
	Partition string
	Name      string
	Bytes     int64
	Rows      int64
	Columns   []string
	CreatedAt time.Time
	UpdatedAt time.Time
}
